#!/usr/bin/env python
""" EngineDialog.py --

 UI generated by GUI Builder Build 219949 on 2006-01-11 23:29:57 from:
    /32bit-root/home/ttedford/python/engine/EngineDialog.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from EngineDialog_ui import EngineDialog

# BEGIN USER CODE global

# END USER CODE global

class CustomEngineDialog(EngineDialog):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # torqueScale_command --
    #
    # Callback to handle torqueScale widget option -command
    def torqueScale_command(self, *args):
        pass

    # velocityScale_command --
    #
    # Callback to handle velocityScale widget option -command
    def velocityScale_command(self, *args):
        pass

    # _scale_1_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _scale_1_command(self, *args):
        pass

    # _scale_2_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _scale_2_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomEngineDialog(root)
    root.title('EngineDialog')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
