""" EngineDialog_ui.py --

	UI generated by GUI Builder Build 219949 on 2006-01-11 23:29:57 from:
	/32bit-root/home/ttedford/python/engine/EngineDialog.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class EngineDialog(object):
	_images = [] # Holds image refs to prevent GC
	def __init__(self, root):	
		# Widget Initialization
		self.torqueScale = Tkinter.Scale(root,
													orient = "horizontal",
													to = 5000)
		
		self.velocityScale = Tkinter.Scale(root,
													  orient = "horizontal",
													  to = 5000)
			
		self.torqueLabel = Tkinter.Label(root,
													text = "Torque")
	
		self.velocityLabel = Tkinter.Label(root,
													  text = "Velocity",
													  )
	
		# widget commands
		self.torqueScale.configure(
			command = self.torqueScale_command
		)
		self.velocityScale.configure(
			command = self.velocityScale_command
		)
	
	
			# Geometry Management
		self.torqueScale.grid(in_    = root,
									 column = 1,
									 row    = 1,
									 columnspan = 1,
									 ipadx = 0,
									 ipady = 0,
									 padx = 0,
									 pady = 0,
									 rowspan = 1,
									 sticky = "ew"
									 )
		self.velocityScale.grid(in_    = root,
										column = 2,
										row    = 1,
										columnspan = 1,
										ipadx = 0,
										ipady = 0,
										padx = 0,
										pady = 0,
										rowspan = 1,
										sticky = "ew"
		)
		self.torqueLabel.grid(in_    = root,
									 column = 1,
									 row    = 2,
									 columnspan = 1,
									 ipadx = 0,
									 ipady = 0,
									 padx = 0,
									 pady = 0,
									 rowspan = 1,
									 sticky = ""
									 )
		self.velocityLabel.grid(in_    = root,
										column = 2,
										row    = 2,
										columnspan = 1,
										ipadx = 0,
										ipady = 0,
										padx = 0,
										pady = 0,
										rowspan = 1,
										sticky = ""
										)
	
	
		# Resize Behavior
		root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
		root.grid_rowconfigure(2, weight = 0, minsize = 39, pad = 0)
		root.grid_columnconfigure(1, weight = 1, minsize = 40, pad = 0)
		root.grid_columnconfigure(2, weight = 1, minsize = 40, pad = 0)
	
	
